#pragma once

/*
 * AEImport — C++ mirror of the .aeimport sidecar JSON format.
 *
 * The .aeimport file sits next to the source asset (e.g. hero.aeimport next to
 * hero.glb) and is generated by the ActionEngine Blender addon.  It carries
 * engine-specific import overrides that are not expressible in glTF/FBX/OBJ.
 *
 * The engine reads it in AssetImporter::Import() and uses its fields to override
 * the caller-supplied ImportSettings before passing them to Assimp.
 *
 * Engine responsibilities (NOT the addon):
 *   - LOD mesh generation from the base mesh
 *   - Collision shape baking (convex hull / trimesh decomposition)
 *   - Jolt Physics body creation
 *   - Animation clip management (AnimationLibrary / AnimationSystem)
 */

#include "core/types.h"
#include <string>
#include <vector>

namespace action {

// Per-mesh override block (matches "mesh_overrides" array in the JSON)
struct AEMeshOverride {
    std::string name;               // Mesh name as it appears in the source file
    std::string collision_type;     // "none" | "convex_hull" | "trimesh" | "capsule" | "box" | "sphere"
    i32  physics_layer  = 0;
    bool cast_shadows   = true;
    float lod_bias      = 1.0f;
    bool is_static      = false;
};

// LOD generation request (matches "lod" block in the JSON)
struct AELodConfig {
    bool  generate     = false;
    i32   level_count  = 4;
    std::vector<float> distances;   // Transition distances per LOD level (level_count - 1 entries)
};

// Top-level import settings read from the sidecar (matches "import_settings" block)
struct AEImportOverrides {
    float scale             = 1.0f;
    bool  flip_uvs          = true;
    bool  generate_normals  = true;
    bool  optimize_meshes   = false;
    std::string up_axis     = "Y";  // "Y" or "Z"
    bool  import_animations = false;
};

// Root sidecar structure
struct AEImport {
    i32  ae_version       = 0;
    std::string source_file;
    std::string blender_version;
    std::string export_timestamp;

    AEImportOverrides   import_settings;
    AELodConfig         lod;
    std::vector<AEMeshOverride>  mesh_overrides;
    std::vector<std::string>     animation_names;

    bool is_valid() const { return ae_version > 0; }

    // Look up a mesh override by name (case-sensitive).
    // Returns nullptr if no override is defined for that mesh.
    const AEMeshOverride* FindMeshOverride(const std::string& mesh_name) const {
        for (const auto& ov : mesh_overrides) {
            if (ov.name == mesh_name) return &ov;
        }
        return nullptr;
    }
};

// -------------------------------------------------------------------------
// Load a .aeimport file from disk.
// Returns an AEImport with ae_version == 0 on failure (use AEImport::is_valid()).
// -------------------------------------------------------------------------
AEImport LoadAEImport(const std::string& filepath);

// Derive the .aeimport sidecar path from an asset filepath.
// E.g. "assets/models/hero.glb" → "assets/models/hero.aeimport"
std::string GetAEImportPath(const std::string& asset_filepath);

} // namespace action
