#pragma once
// Auto-generated by ActionEngine Editor — do not edit manually.
// Rebuild the project after creating or removing scripts.

#include "game/scripts/VikingMovement.h"

namespace action {

inline void RegisterUserScripts() {
    REGISTER_SCRIPT(VikingMovement);
}

} // namespace action
